mysite/myapp/urls.py
from django.contrib import admin
from django.urls import path
from myapp import views


app_name = 'myapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('book/<int:book_id>/', views.detail, name='detail'),
    path('add/', views.add_book, name='add_book'),
    path('update/<int:book_id>/', views.update, name='update'),
    path('delete/<int:book_id>/', views.delete, name='delete'),
]

mysite/mysite/urls.py
from django.contrib import admin
# import include in order to link myapp urls
from django.urls import path, include
from .import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # link to a separate myapp urls.py file
    path('', include('myapp.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/myapp/models.py
from django.db import models

# Create your models here.

class Book(models.Model):

    def __str__(self):
        return self.name
        
    name = models.CharField(max_length=100)
    desc = models.CharField(max_length=300)
    price = models.IntegerField()
    book_image = models.ImageField(default='default.jpg',upload_to='book_images/')

mysite/myapp/forms.py
from django import forms
from .models import Book

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['name', 'desc', 'book_image', 'price']
    

mysite/myapp/views.py
from django.core.exceptions import RequestAborted
from django.shortcuts import render,redirect
from django.http import HttpResponse
# Import your models here.
from .models import Book
from .forms import BookForm


# Create your views here.

def index(request):
    book_list = Book.objects.all()
    context = {
        'book_list' : book_list
    }
    return render(request, 'myapp/index.html', context)

def detail(request,book_id):
    book = Book.objects.get(id=book_id)
    return render(request, 'myapp/detail.html', {'book':book}) 

def add_book(request):
    # form submission
    if request.method == 'POST':
        name = request.POST.get('name',)
        desc = request.POST.get('desc',)
        price = request.POST.get('price',)
        book_image = request.FILES['book_image']

        book = Book(name=name, desc=desc, price=price, book_image=book_image)
        book.save()
        return redirect('/')
    return render(request, 'myapp/add_book.html')

# NOTE: as i understand it, the flow is that the id of the book is passed as an integer into the url first, then the url takes that value and passes it into the view (which is why the view accepts the id as an argument)
def update(request,book_id):
    book = Book.objects.get(id=book_id)
    form = BookForm(request.POST or None, request.FILES, instance=book)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'myapp/edit.html',{'book':book, 'form':form})

def delete(request,book_id):
    
    if request.method=='POST':
        book = Book.objects.get(id=book_id)
        book.delete()
        return redirect('/')
    return render(request, 'myapp/delete.html')

mysite/myapp/templates/myapp/add_book.html
{% extends 'myapp/base.html' %}
{% block body %}
<form method='POST' enctype="multipart/form-data">
    {% csrf_token %}
    <input type='text' name='name' id='name' placeholder="Enter the name of your book"><br>
    <input type='text' name='desc' id='desc' placeholder="Enter the description"><br>
    <input type='text' name='price' id='price' placeholder="Enter the price"><br>
    <input type='file' name='book_image' id='book_image'><br>
    <input type='submit'>
</form>

{% endblock %}

mysite/myapp/templates/myapp/base.html
<! -- load the css stylesheet: -->
{% load static %}
<html>
    <head>
        <! -- the bootstrap link should be at the top of the head tag -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel='stylesheet' href="{% static 'myapp/style.css' %}">
    </head>

    <body>
        <!-- Image and text -->
        <nav class="navbar navbar-dark bg-dark">
            <a class="navbar-brand" href="{% url 'myapp:index' %}">
            Book Store
            </a>
        </nav>
    
        {% block body %}
        
        {% endblock %}
    </body>
</html>

mysite/myapp/templates/myapp/delete.html
{% extends 'myapp/base.html' %}

{% block body %}
<form method='POST'>
    {% csrf_token %}
    Are you sure you want to delete this book?<br>
    <input type='submit'>
</form>

{% endblock %}

mysite/myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}

{% block body %}
<div class="container">
    <br>
    <div class="row">
        <div class="col-md-6">
            <img width = '400' src='{{book.book_image.url}}'>
        </div>
        <div class="col-md-6">
            <h2>{{book.name}}</h2>
            <h5>Description: {{book.desc}}</h6>
            <h6>Price: ${{book.price}}</h6>
            <a class="btn btn-warning" href='{% url "myapp:update" book.id %}'>Update</a>
            <a class="btn btn-danger" href='{% url "myapp:delete" book.id %}'>Delete</a>
        </div>
    </div>
</div>


{% endblock %}
 

mysite/myapp/templates/myapp/edit.html
{% extends 'myapp/base.html' %}

{% block body %}
<form method='POST' enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type='submit'>
</form>

{% endblock %}

mysite/myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}

{% block body %}
<div class="container">
    <div class="row">
        {% for book in book_list %}
        <div class="col-md-3">
            <div class="card">
                <img height='350' class="card-img-top" src="{{book.book_image.url}}">
                <div class="card-body">
                    <h5 class="card-title"><a href='{% url "myapp:detail" book.id %}'>{{book.name}}</a></h5>
                    <p class="card-text">${{book.price}}</p>
                    <a class="btn btn-primary" href='{% url "myapp:detail" book.id %}'>View Details</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <h6><a href="{% url 'myapp:add_book' %}">Add Book</a></h6>
</div>

{% endblock %}